version: '2'

services:
  redis-master:
    container_name: redis
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=123
    networks:
      - general
    volumes:
      - redis_data
  redis-replica:
    image: redis:4.0.5-alpine
    container_name: redis_rep
    ports:
      - 6379:6379
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=my_master_password
      - REDIS_PASSWORD=123
    networks:
      - general
volumes:
  redis_data:
    driver: local
networks:
  general:
    external: true
